# Generated by Django 4.1.2 on 2022-10-20 22:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('bank_name', models.CharField(max_length=128)),
                ('country', models.CharField(max_length=128)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='userapp.account')),
            ],
        ),
    ]
