# Generated by Django 4.1.2 on 2022-10-20 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prometeo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='account',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='bank_uuid',
        ),
    ]
