# Generated by Django 4.1.2 on 2022-10-21 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prometeo', '0002_remove_bankaccount_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='bank_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='country',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
